### ISSUE TITLE
这是腾讯开发的吗?也太糟糕了吧,不相信是大公司开发的

### ISSUE THREAD

**Issue by shunxingzhe** [tencentyun/qcloud-iot-explorer-BLE-sdk-embedded#2]
nordic 52832的工程,下载后关键的几个文件找不到,这里有ble_qiot标识的文件
编译出来64个error,我的天!

**Comment by idiotstone** [comment]
你好，`nordic 52832`的例程使用的是`nrf sdk ` 版本是 `nRF5_SDK_15.3.0_59ac345`，[下载地址](https://www.nordicsemi.com/Software-and-tools/Software/nRF5-SDK/Download)
请参考示例工程的[readme](https://github.com/tencentyun/qcloud-iot-explorer-BLE-sdk-embedded/blob/master/samples/nrf52832/readme.md)
